# Generated by Django 6.0.5 on 2026-05-24 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "emotion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("disciplined", "Disciplined"),
                            ("fomo", "FOMO"),
                            ("revenge", "Revenge Trade"),
                            ("patient", "Patient"),
                            ("greedy", "Greedy"),
                            ("fearful", "Fearful"),
                            ("confident", "Confident"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mistake",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early_exit", "Exited Too Early"),
                            ("late_exit", "Exited Too Late"),
                            ("oversized", "Position Too Large"),
                            ("no_plan", "No Plan"),
                            ("moved_sl", "Moved Stop Loss"),
                            ("chased", "Chased Entry"),
                            ("none", "No Mistake"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(blank=True, null=True, upload_to="screenshots/"),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entry",
                        to="trades.trade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
